// Codes INSEE département + région, requis par l'API recherche-entreprises.api.gouv.fr
export interface CodeLabel { code: string; label: string }

export const FRENCH_DEPARTMENTS_WITH_CODES: CodeLabel[] = [
  { code: '01', label: 'AIN' }, { code: '02', label: 'AISNE' }, { code: '03', label: 'ALLIER' },
  { code: '04', label: 'ALPES-DE-HAUTE-PROVENCE' }, { code: '05', label: 'HAUTES-ALPES' }, { code: '06', label: 'ALPES-MARITIMES' },
  { code: '07', label: 'ARDÈCHE' }, { code: '08', label: 'ARDENNES' }, { code: '09', label: 'ARIÈGE' },
  { code: '10', label: 'AUBE' }, { code: '11', label: 'AUDE' }, { code: '12', label: 'AVEYRON' },
  { code: '13', label: 'BOUCHES-DU-RHÔNE' }, { code: '14', label: 'CALVADOS' }, { code: '15', label: 'CANTAL' },
  { code: '16', label: 'CHARENTE' }, { code: '17', label: 'CHARENTE-MARITIME' }, { code: '18', label: 'CHER' },
  { code: '19', label: 'CORRÈZE' }, { code: '2A', label: 'CORSE-DU-SUD' }, { code: '2B', label: 'HAUTE-CORSE' },
  { code: '21', label: "CÔTE-D'OR" }, { code: '22', label: "CÔTES-D'ARMOR" }, { code: '23', label: 'CREUSE' },
  { code: '24', label: 'DORDOGNE' }, { code: '25', label: 'DOUBS' }, { code: '26', label: 'DRÔME' },
  { code: '27', label: 'EURE' }, { code: '28', label: 'EURE-ET-LOIR' }, { code: '29', label: 'FINISTÈRE' },
  { code: '30', label: 'GARD' }, { code: '31', label: 'HAUTE-GARONNE' }, { code: '32', label: 'GERS' },
  { code: '33', label: 'GIRONDE' }, { code: '34', label: 'HÉRAULT' }, { code: '35', label: 'ILLE-ET-VILAINE' },
  { code: '36', label: 'INDRE' }, { code: '37', label: 'INDRE-ET-LOIRE' }, { code: '38', label: 'ISÈRE' },
  { code: '39', label: 'JURA' }, { code: '40', label: 'LANDES' }, { code: '41', label: 'LOIR-ET-CHER' },
  { code: '42', label: 'LOIRE' }, { code: '43', label: 'HAUTE-LOIRE' }, { code: '44', label: 'LOIRE-ATLANTIQUE' },
  { code: '45', label: 'LOIRET' }, { code: '46', label: 'LOT' }, { code: '47', label: 'LOT-ET-GARONNE' },
  { code: '48', label: 'LOZÈRE' }, { code: '49', label: 'MAINE-ET-LOIRE' }, { code: '50', label: 'MANCHE' },
  { code: '51', label: 'MARNE' }, { code: '52', label: 'HAUTE-MARNE' }, { code: '53', label: 'MAYENNE' },
  { code: '54', label: 'MEURTHE-ET-MOSELLE' }, { code: '55', label: 'MEUSE' }, { code: '56', label: 'MORBIHAN' },
  { code: '57', label: 'MOSELLE' }, { code: '58', label: 'NIÈVRE' }, { code: '59', label: 'NORD' },
  { code: '60', label: 'OISE' }, { code: '61', label: 'ORNE' }, { code: '62', label: 'PAS-DE-CALAIS' },
  { code: '63', label: 'PUY-DE-DÔME' }, { code: '64', label: 'PYRÉNÉES-ATLANTIQUES' }, { code: '65', label: 'HAUTES-PYRÉNÉES' },
  { code: '66', label: 'PYRÉNÉES-ORIENTALES' }, { code: '67', label: 'BAS-RHIN' }, { code: '68', label: 'HAUT-RHIN' },
  { code: '69', label: 'RHÔNE' }, { code: '70', label: 'HAUTE-SAÔNE' }, { code: '71', label: 'SAÔNE-ET-LOIRE' },
  { code: '72', label: 'SARTHE' }, { code: '73', label: 'SAVOIE' }, { code: '74', label: 'HAUTE-SAVOIE' },
  { code: '75', label: 'PARIS' }, { code: '76', label: 'SEINE-MARITIME' }, { code: '77', label: 'SEINE-ET-MARNE' },
  { code: '78', label: 'YVELINES' }, { code: '79', label: 'DEUX-SÈVRES' }, { code: '80', label: 'SOMME' },
  { code: '81', label: 'TARN' }, { code: '82', label: 'TARN-ET-GARONNE' }, { code: '83', label: 'VAR' },
  { code: '84', label: 'VAUCLUSE' }, { code: '85', label: 'VENDÉE' }, { code: '86', label: 'VIENNE' },
  { code: '87', label: 'HAUTE-VIENNE' }, { code: '88', label: 'VOSGES' }, { code: '89', label: 'YONNE' },
  { code: '90', label: 'TERRITOIRE-DE-BELFORT' }, { code: '91', label: 'ESSONNE' }, { code: '92', label: 'HAUTS-DE-SEINE' },
  { code: '93', label: 'SEINE-SAINT-DENIS' }, { code: '94', label: 'VAL-DE-MARNE' }, { code: '95', label: "VAL-D'OISE" },
  { code: '971', label: 'GUADELOUPE' }, { code: '972', label: 'MARTINIQUE' }, { code: '973', label: 'GUYANE' },
  { code: '974', label: 'LA RÉUNION' }, { code: '976', label: 'MAYOTTE' },
].sort((a, b) => a.label.localeCompare(b.label, 'fr'));

export const FRENCH_REGIONS_WITH_CODES: CodeLabel[] = [
  { code: '84', label: 'AUVERGNE-RHÔNE-ALPES' },
  { code: '27', label: 'BOURGOGNE-FRANCHE-COMTÉ' },
  { code: '53', label: 'BRETAGNE' },
  { code: '24', label: 'CENTRE-VAL DE LOIRE' },
  { code: '94', label: 'CORSE' },
  { code: '44', label: 'GRAND EST' },
  { code: '32', label: 'HAUTS-DE-FRANCE' },
  { code: '11', label: 'ÎLE-DE-FRANCE' },
  { code: '28', label: 'NORMANDIE' },
  { code: '75', label: 'NOUVELLE-AQUITAINE' },
  { code: '76', label: 'OCCITANIE' },
  { code: '52', label: 'PAYS DE LA LOIRE' },
  { code: '93', label: "PROVENCE-ALPES-CÔTE D'AZUR" },
  { code: '01', label: 'GUADELOUPE' },
  { code: '02', label: 'MARTINIQUE' },
  { code: '03', label: 'GUYANE' },
  { code: '04', label: 'LA RÉUNION' },
  { code: '06', label: 'MAYOTTE' },
].sort((a, b) => a.label.localeCompare(b.label, 'fr'));
