
export const FRENCH_REGIONS = [
  "AUVERGNE-RHÔNE-ALPES",
  "BOURGOGNE-FRANCHE-COMTÉ", 
  "BRETAGNE",
  "CENTRE-VAL DE LOIRE",
  "CORSE",
  "GRAND EST",
  "GUADELOUPE",
  "GUYANE",
  "HAUTS-DE-FRANCE",
  "ÎLE-DE-FRANCE",
  "LA RÉUNION",
  "MARTINIQUE",
  "MAYOTTE",
  "NORMANDIE",
  "NOUVELLE-AQUITAINE",
  "OCCITANIE",
  "PAYS DE LA LOIRE",
  "PROVENCE-ALPES-CÔTE D'AZUR"
].sort();
