// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp, auth } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-proprietes.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/supabaseForUser.ts
import { createClient } from "npm:@supabase/supabase-js@2.110.9";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var notAuthenticated = () => ({
  content: [{ type: "text", text: "Non authentifi\xE9 : reconnectez le connecteur." }],
  isError: true
});
var errorResult = (message) => ({
  content: [{ type: "text", text: message }],
  isError: true
});
var jsonResult = (payload) => ({
  content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
  structuredContent: payload
});
async function resolveProprieteId(supabase, ref) {
  const isUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(ref);
  const query = supabase.from("proprietes").select("id, nom, slug").limit(1);
  const { data } = isUuid ? await query.eq("id", ref) : await query.eq("slug", ref);
  const row = (data ?? [])[0];
  return row ?? null;
}

// src/lib/mcp/tools/list-proprietes.ts
var list_proprietes_default = defineTool({
  name: "list_proprietes",
  title: "Lister les propri\xE9t\xE9s",
  description: "Liste les propri\xE9t\xE9s (jardins, domaines, sites) accessibles \xE0 l'utilisateur connect\xE9, avec id, nom, slug, ville et r\xF4le.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("get_user_apps_access");
    if (error) return errorResult(error.message);
    const access = data ?? {};
    return jsonResult({
      proprietes: access.proprietesAccessibles ?? [],
      proprietePrincipaleId: access.proprietePrincipaleId ?? null,
      hasMarcheurAccess: !!access.hasMarcheurAccess
    });
  }
});

// src/lib/mcp/tools/get-propriete-overview.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var get_propriete_overview_default = defineTool2({
  name: "get_propriete_overview",
  title: "Fiche propri\xE9t\xE9",
  description: "Fiche compl\xE8te d'une propri\xE9t\xE9 : identit\xE9, parcelles cadastrales (surfaces, g\xE9om\xE9trie), \xE9v\xE9nements de marche li\xE9s et contributeurs.",
  inputSchema: {
    propriete: z.string().min(1).describe("Identifiant (UUID) ou slug de la propri\xE9t\xE9, ex. 'jardin-monde-deviat'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ propriete }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const target = await resolveProprieteId(supabase, propriete);
    if (!target) return errorResult(`Propri\xE9t\xE9 introuvable ou non accessible : ${propriete}`);
    const [{ data: fiche }, parcelles, events] = await Promise.all([
      supabase.from("proprietes").select("*").eq("id", target.id).maybeSingle(),
      supabase.rpc("list_propriete_parcelles", { _propriete_id: target.id }),
      supabase.from("propriete_marche_events").select("marche_events(id, title, date_marche, exploration_id, slug)").eq("propriete_id", target.id)
    ]);
    if (parcelles.error) return errorResult(parcelles.error.message);
    return jsonResult({
      propriete: fiche ?? { id: target.id, nom: target.nom, slug: target.slug },
      parcelles: parcelles.data ?? [],
      surfaceTotaleM2: (parcelles.data ?? []).reduce(
        (s, p) => s + (p.contenance_m2 ?? 0),
        0
      ),
      evenements: (events.data ?? []).map((r) => r.marche_events).filter(Boolean)
    });
  }
});

// src/lib/mcp/tools/get-propriete-biodiversity.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_propriete_biodiversity_default = defineTool3({
  name: "get_propriete_biodiversity",
  title: "Synth\xE8se biodiversit\xE9",
  description: "Synth\xE8se biodiversit\xE9 d'une propri\xE9t\xE9 : nombre total d'esp\xE8ces, r\xE9partition par r\xE8gne, top esp\xE8ces, dernier \xE9v\xE9nement et derni\xE8re observation. Source identique \xE0 celle affich\xE9e dans l'application.",
  inputSchema: {
    propriete: z2.string().min(1).describe("Identifiant (UUID) ou slug de la propri\xE9t\xE9.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ propriete }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const target = await resolveProprieteId(supabase, propriete);
    if (!target) return errorResult(`Propri\xE9t\xE9 introuvable ou non accessible : ${propriete}`);
    const { data, error } = await supabase.rpc("get_propriete_biodiversity", {
      p_propriete_id: target.id
    });
    if (error) return errorResult(error.message);
    return jsonResult({ propriete: target, biodiversite: data ?? {} });
  }
});

// src/lib/mcp/tools/get-propriete-species-pool.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var normName = (s) => (s || "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim();
var get_propriete_species_pool_default = defineTool4({
  name: "get_propriete_species_pool",
  title: "Pool d'esp\xE8ces observ\xE9es",
  description: "Liste d\xE9dupliqu\xE9e des esp\xE8ces observ\xE9es sur une propri\xE9t\xE9 (nom scientifique, nom commun, r\xE8gne, famille, nombre d'observations, derni\xE8re observation). Mati\xE8re premi\xE8re pour auditer les comptages affich\xE9s.",
  inputSchema: {
    propriete: z3.string().min(1).describe("Identifiant (UUID) ou slug de la propri\xE9t\xE9."),
    limit: z3.number().int().min(1).max(1e3).nullable().describe("Nombre maximum d'esp\xE8ces retourn\xE9es (d\xE9faut 300). Null = 300.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ propriete, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const target = await resolveProprieteId(supabase, propriete);
    if (!target) return errorResult(`Propri\xE9t\xE9 introuvable ou non accessible : ${propriete}`);
    const { data: links, error: linkErr } = await supabase.from("propriete_marche_events").select("marche_events!inner(exploration_id)").eq("propriete_id", target.id);
    if (linkErr) return errorResult(linkErr.message);
    const explorationIds = Array.from(
      new Set(
        (links ?? []).map((r) => r.marche_events?.exploration_id).filter((v) => !!v)
      )
    );
    const bucket = /* @__PURE__ */ new Map();
    for (const explorationId of explorationIds) {
      const { data, error } = await supabase.rpc("get_exploration_species_pool", {
        p_exploration_id: explorationId
      });
      if (error) return errorResult(error.message);
      for (const sp of data?.species ?? []) {
        const scientific = sp.scientific_name || sp.common_name || sp.key || "";
        const key = normName(scientific);
        if (!key) continue;
        const prev = bucket.get(key);
        if (prev) {
          prev.observations += sp.observations ?? 0;
          if (sp.last_seen && (!prev.lastSeen || sp.last_seen > prev.lastSeen)) {
            prev.lastSeen = sp.last_seen;
          }
          prev.common = prev.common ?? sp.common_name ?? null;
        } else {
          bucket.set(key, {
            scientific,
            common: sp.common_name ?? null,
            kingdom: sp.kingdom ?? null,
            family: sp.family ?? null,
            iconicTaxon: sp.iconic_taxon ?? null,
            observations: sp.observations ?? 0,
            lastSeen: sp.last_seen ?? null
          });
        }
      }
    }
    const all = Array.from(bucket.values()).sort((a, b) => b.observations - a.observations);
    const max = limit ?? 300;
    return jsonResult({
      propriete: target,
      explorationIds,
      speciesTotal: all.length,
      observationsTotal: all.reduce((s, sp) => s + sp.observations, 0),
      returned: Math.min(max, all.length),
      species: all.slice(0, max)
    });
  }
});

// src/lib/mcp/tools/get-propriete-diagnostic.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var get_propriete_diagnostic_default = defineTool5({
  name: "get_propriete_diagnostic",
  title: "Diagnostic (J'observe / J'analyse / J'identifie)",
  description: "Donn\xE9es brutes des 3 \xE9tapes du diagnostic d'une propri\xE9t\xE9 : observations du site, analyse du sol (pr\xE9l\xE8vements, structure, texture, pH, vie) et diagnostic flore (plantes observ\xE9es, concordance, score ICG).",
  inputSchema: {
    propriete: z4.string().min(1).describe("Identifiant (UUID) ou slug de la propri\xE9t\xE9."),
    etape: z4.enum(["observe", "sol", "flore", "toutes"]).nullable().describe("\xC9tape \xE0 retourner. Null = toutes.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ propriete, etape }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const target = await resolveProprieteId(supabase, propriete);
    if (!target) return errorResult(`Propri\xE9t\xE9 introuvable ou non accessible : ${propriete}`);
    const want = etape ?? "toutes";
    const out = { propriete: target };
    if (want === "observe" || want === "toutes") {
      const { data, error } = await supabase.from("propriete_observations").select("*").eq("propriete_id", target.id).maybeSingle();
      if (error && error.code !== "PGRST116") return errorResult(error.message);
      out.observe = data ?? null;
    }
    if (want === "sol" || want === "toutes") {
      const { data, error } = await supabase.from("propriete_soil_diagnostics").select("*").eq("propriete_id", target.id).maybeSingle();
      if (error && error.code !== "PGRST116") return errorResult(error.message);
      out.sol = data ?? null;
    }
    if (want === "flore" || want === "toutes") {
      const { data, error } = await supabase.from("propriete_flora_diagnostics").select("*").eq("propriete_id", target.id).maybeSingle();
      if (error && error.code !== "PGRST116") return errorResult(error.message);
      out.flore = data ?? null;
    }
    return jsonResult(out);
  }
});

// src/lib/mcp/tools/get-propriete-observation-points.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^3.25.76";
var get_propriete_observation_points_default = defineTool6({
  name: "get_propriete_observation_points",
  title: "Points d'observation g\xE9olocalis\xE9s",
  description: "Observations g\xE9olocalis\xE9es rattach\xE9es \xE0 une propri\xE9t\xE9 (esp\xE8ce, coordonn\xE9es, date, source marcheur ou iNaturalist), corrections GPS \xE9ditoriales d\xE9j\xE0 appliqu\xE9es. Utile pour v\xE9rifier les cartes et les comptages.",
  inputSchema: {
    propriete: z5.string().min(1).describe("Identifiant (UUID) ou slug de la propri\xE9t\xE9."),
    espece: z5.string().nullable().describe("Filtre optionnel sur le nom scientifique ou commun (recherche partielle). Null = toutes."),
    limit: z5.number().int().min(1).max(2e3).nullable().describe("Nombre maximum de points retourn\xE9s (d\xE9faut 500). Null = 500.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ propriete, espece, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const target = await resolveProprieteId(supabase, propriete);
    if (!target) return errorResult(`Propri\xE9t\xE9 introuvable ou non accessible : ${propriete}`);
    const { data: links, error: linkErr } = await supabase.from("propriete_marche_events").select("marche_events!inner(exploration_id)").eq("propriete_id", target.id);
    if (linkErr) return errorResult(linkErr.message);
    const explorationIds = Array.from(
      new Set(
        (links ?? []).map((r) => r.marche_events?.exploration_id).filter((v) => !!v)
      )
    );
    const needle = (espece ?? "").toLowerCase().trim();
    const points = [];
    for (const explorationId of explorationIds) {
      const { data, error } = await supabase.rpc("get_exploration_species_pool", {
        p_exploration_id: explorationId
      });
      if (error) return errorResult(error.message);
      for (const sp of data?.species ?? []) {
        const scientific = sp.scientific_name || sp.key || "";
        if (needle && !scientific.toLowerCase().includes(needle) && !(sp.common_name || "").toLowerCase().includes(needle)) {
          continue;
        }
        const attrs = [
          ...Array.isArray(sp.marcheur_attrs) ? sp.marcheur_attrs : [],
          ...Array.isArray(sp.attributions) ? sp.attributions : []
        ];
        for (const a of attrs) {
          const lat = a.lat ?? a.latitude ?? null;
          const lng = a.lng ?? a.longitude ?? null;
          if (lat == null || lng == null) continue;
          points.push({
            scientificName: scientific,
            commonName: sp.common_name ?? null,
            kingdom: sp.kingdom ?? null,
            lat,
            lng,
            observationDate: a.observed_on ?? a.observation_date ?? a.date ?? null,
            source: a.source ?? (a.inat_observation_id ? "inaturalist" : "marcheur"),
            observer: a.observer_name ?? a.observer_login ?? null,
            explorationId
          });
        }
      }
    }
    const max = limit ?? 500;
    return jsonResult({
      propriete: target,
      explorationIds,
      pointsTotal: points.length,
      returned: Math.min(max, points.length),
      points: points.slice(0, max)
    });
  }
});

// src/lib/mcp/index.ts
var projectRef = "xzbunrtgbfbhinkzkzhf";
var mcp_default = defineMcp({
  name: "la-frequence-du-vivant",
  title: "La Fr\xE9quence du Vivant",
  version: "0.1.0",
  instructions: "Acc\xE8s en lecture seule aux donn\xE9es des propri\xE9t\xE9s (jardins, domaines) de La Fr\xE9quence du Vivant : biodiversit\xE9 observ\xE9e, pool d'esp\xE8ces d\xE9dupliqu\xE9, points d'observation g\xE9olocalis\xE9s et diagnostics (J'observe / J'analyse le sol / J'identifie la flore, score ICG). Chaque appel agit au nom de l'utilisateur connect\xE9 : seules les propri\xE9t\xE9s auxquelles il a acc\xE8s sont visibles. Utilisez `list_proprietes` d'abord pour obtenir les identifiants ou slugs.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_proprietes_default,
    get_propriete_overview_default,
    get_propriete_biodiversity_default,
    get_propriete_species_pool_default,
    get_propriete_diagnostic_default,
    get_propriete_observation_points_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
