INSERT INTO public.frequence_citations (texte, auteur, oeuvre, url) VALUES
('Dans chaque promenade avec la nature, on reçoit bien plus que ce qu''on cherche.', 'John Muir', 'Unpublished Journals (1938)', 'https://vault.sierraclub.org/john_muir_exhibit/writings/'),
('Vieil étang — une grenouille plonge, bruit de l''eau.', 'Bashō', 'Furu ike ya (1686)', 'https://fr.wikisource.org/wiki/Bashō'),
('Le vrai voyage de découverte ne consiste pas à chercher de nouveaux paysages, mais à avoir de nouveaux yeux.', 'Marcel Proust', 'La Prisonnière (1923)', 'https://gallica.bnf.fr/ark:/12148/bpt6k1049554b'),
('La nature ne se presse jamais, et pourtant tout est accompli.', 'Lao Tseu', 'Tao Te King, ch. 73', 'https://www.sacred-texts.com/tao/taote.htm'),
('Ce n''est pas ce que vous regardez qui compte, c''est ce que vous voyez.', 'Henry David Thoreau', 'Journal (1851)', 'https://www.walden.org/thoreau/'),
('Un bon paysage sonore est une composition dont les éléments sont en équilibre.', 'R. Murray Schafer', 'The Soundscape (1977)', 'https://www.worldcat.org/title/3348220'),
('Le grand orchestre animal est un bioindicateur plus fiable que n''importe quel instrument.', 'Bernie Krause', 'The Great Animal Orchestra (2012)', 'https://www.worldcat.org/title/773667029'),
('Les forêts précèdent les peuples, les déserts les suivent.', 'Chateaubriand', 'Mémoires d''outre-tombe, t. IV (1848)', 'https://gallica.bnf.fr/essentiels/chateaubriand/memoires-outre-tombe'),
('On protège ce qu''on aime. On aime ce qu''on connaît.', 'Jacques-Yves Cousteau', 'Interview TV, Antenne 2 (1971)', 'https://www.cousteau.org/'),
('Un paysage est un état d''âme.', 'Henri-Frédéric Amiel', 'Journal intime, 31 oct. 1852', 'https://www.e-rara.ch/doi/10.3931/e-rara-26053'),
('Le monde est plein de choses magiques, attendant patiemment que nos sens s''aiguisent.', 'W.B. Yeats', 'The Celtic Twilight (1893)', 'https://www.gutenberg.org/ebooks/7128'),
('Marcher, c''est habiter le monde avec ses pieds.', 'David Le Breton', 'Éloge de la marche (2000)', 'https://www.worldcat.org/title/44753659'),
('Celui qui marche ne peut porter que l''essentiel.', 'Sylvain Tesson', 'Petit traité sur l''immensité du monde (2005)', 'https://www.worldcat.org/title/60671883'),
('Le monde se révèle à ceux qui marchent.', 'Jean-Jacques Rousseau', 'Les Confessions, Livre IV (1782)', 'https://gallica.bnf.fr/essentiels/rousseau/confessions'),
('La géopoétique est l''art d''habiter la Terre en poète.', 'Kenneth White', 'Le Plateau de l''Albatros (1994)', 'https://www.worldcat.org/title/32348793'),
('Chaque espèce disparue est une page arrachée au livre du vivant.', 'Jane Goodall', 'Reason for Hope (1999)', 'https://www.worldcat.org/title/41473758'),
('La biodiversité est la bibliothèque du vivant. Chaque espèce est un livre irremplaçable.', 'Edward O. Wilson', 'The Diversity of Life (1992)', 'https://www.worldcat.org/title/25632830'),
('Écouter la forêt, c''est lire un livre dont chaque page est un son.', 'Bernie Krause', 'Wild Soundscapes (2002)', 'https://www.worldcat.org/title/50027771'),
('Le silence de la nature est sa plus belle conversation.', 'Bashō', 'Oku no Hosomichi (1689)', 'https://fr.wikisource.org/wiki/La_Sente_étroite_du_Bout-du-Monde'),
('Un oiseau ne chante pas parce qu''il a une réponse. Il chante parce qu''il a un chant.', 'Maya Angelou', 'I Know Why the Caged Bird Sings (1969)', 'https://www.worldcat.org/title/12850'),
('Le chant du merle noir dessine la carte d''un territoire invisible.', 'Rachel Carson', 'Silent Spring (1962)', 'https://www.worldcat.org/title/555184'),
('Quand le dernier arbre aura été abattu, nous réaliserons que l''argent ne se mange pas.', 'Proverbe Alanis (attribué)', 'Cité dans Greenpeace, années 1970', 'https://www.snopes.com/fact-check/last-tree-cut-down/'),
('L''homme n''a pas tissé la toile de la vie, il n''en est qu''un fil.', 'Ted Perry (attribué à Chef Seattle)', 'Home, film ABC (1972)', 'https://www.snopes.com/fact-check/chief-seattle/'),
('La Terre n''est pas un environnement, c''est un organisme vivant.', 'James Lovelock', 'Gaia: A New Look at Life on Earth (1979)', 'https://www.worldcat.org/title/5360287'),
('Nous n''héritons pas de la terre de nos ancêtres, nous l''empruntons à nos enfants.', 'Antoine de Saint-Exupéry', 'Terre des hommes (1939)', 'https://www.worldcat.org/title/1738850');